add cygwin support, add warn on failed ping calls

diff --git a/scripts/top_ping b/scripts/top_ping
--- a/scripts/top_ping
+++ b/scripts/top_ping
@@ -3,13 +3,22 @@
 #quick detect host with best response
 rm -rf /tmp/*.-ping
 
-for h in {amazon,yahoo,softwareag,ebay,google,youtube.com}.com {pscu,gnu}.org
+#linux or cygwin?
+if which cygpath 2>&1 > /dev/null
+then cw=true
+else cw=false
+fi
+
+for h in aquarius-{va,bg,den,dae} {amazon,yahoo,softwareag,ebay,google,youtube.com}.com {pscu,gnu}.org
 do
-   ping -c 3 -w 3 $h > /tmp/$h.-ping 2>/tmp/duh.-ping& #&find fast!
+   ping -$($cw && echo n || echo c) 3 -w 3 $h > /tmp/$h.-ping 2>&1& #&find fast!
 done; wait
 
 #unix brute force in action when in doubt
 grep "time=[^ ]\+" /tmp/*.-ping -o|sort -t '=' -k2n |head -1|sed 's~/tmp/\(.*\)\.-ping.*~\1~'
 
-test -s /tmp/duh.-ping && { echo 'warn $0: some host(s) do not response' 1>&2; } ||:
+#test -s /tmp/duh.-ping && { echo 'warn $0: some host(s) do not response' 1>&2; } ||:
+
+#warn on failed pings
+(grep 'could not find' /tmp/*.-ping && echo warn: no response on some hosts above ||:) 1>&2
 
